### ISSUE TITLE
Signup issue

### ISSUE THREAD

**Issue by SahidAhmed09** [DigitalFortressPvtLtd/MukhamApp-Feedback#3]
Didn't get the verification mail for signup.

**Comment by MidhunAkash** [comment]
Check spam

**Comment by MidhunAkash** [comment]
Did you use the resend button?
in case if it was not received

**Comment by MidhunAkash** [comment]
Also, put a recorded video here will help to resolve better

**Comment by SahidAhmed09** [comment]
https://github.com/DigitalFortressPvtLtd/MukhamApp-Feedback/assets/127042654/24f97699-3219-443f-959f-2abeeb44b5ea

Here is the video reference to it.

**Comment by MidhunAkash** [comment]
Check the spam folder after few seconds
